version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore:1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./SaleMan.sln && dotnet publish ./SaleMan.sln -c Release -o ./obj/Docker/publish"
